---
title: "Using Chat GPT"
---

ChatGPT is a large language model that was used to assist with this assignment. The purpose of using ChatGPT was to assess its ability to help with the assignment and identify areas where it is helpful and identify any short comings.

A number of different types of requests were made and its performance on these different types of requests varied, which are detailed below.

**Open ended questions/Asking for guidance:**

The first types of questions asked to ChatGPT were questions that were quite broad questions, asking for guidance and direction. For example: "What is the best way to perform sentiment analysis of speeches in R?" or "What are the major application areas for sentiment analysis?". For question like these ChatGPT was quite helpful and provided lists with useful information which was beneficial for giving some direction on what to do or write about in the report. This included giving steps one could follow in R with associated code as well as lists of application areas with brief descriptions of how sentiment analysis is applied.

**Providing literature:**

The second task that ChatGPT was attempted to be used for was to provide papers and textbooks for a brief literature review. Questions asked were "Can you recommend papers or textbooks on sentiment analysis for the purpose of a literature review?" and "Please also provide some papers for a brief literature review for Topic Modelling? Particularly any papers that have done topic modelling for presidential speeches". Some papers provided were helpful and contained the right type of information that was being looked for however some of the papers it suggested seemed to not exist or were written by different authors then those specified by ChatGPT. In addition, a number of Machine Learning papers linked to sentiment analysis were recommended which while potentially interesting one would not necessarily be looking for when looking for basic sentiment analysis information. This was however not specified in the prompt and one needs to maybe be more specific with what type of literature one is looking for.

**Assistance with code:**

A number of prompts were give to ChatGPT regarding code and how to fix errors in R or create certain plots. This is one area that ChatGPT performs well in and is able to take a request for how to do something and produce chunks of code that execute the task. One area that ChatGPT did not do particularly well in was identifying why a particular error was occurring in R. For example with the S4 objects that are created when one does LDA analysis. ChatGPT did not know that one cannot make use of the \$ operator for these S4 objects. Even after giving it the R error which specifies that this is the case, it still did not produce the correct code. The prompt had to be modified to specify that this is the case and request the correct operator before ChatGPT was able to give the correct code.

**Assistance with write up:**

The final task for which the ChatGPT tool was used was to see its ability in writing up some of the report. For this purpose the prompt given was the introduction and asked to edit it and make it 'better' for a scientific paper. This is one area where ChatGPT does not perform particularly well. While it is able to write and generate text that makes sense and is good in terms of structure, the language used is quite 'flowery' and it uses many unnecessary words. This makes it very obvious that it was written by a Large Language Model and it does not convey the same tone that an academic would write. The response of model in terms of these write up questions were not used in the report because the responses were not particularly good.

Overall it was found that while ChatGPT is a useful tool and can provide one with ideas to get start as well as code for when one is not sure what to do, one needs to be wary of taking everything it says without checking it. In addition sometimes its 'fixes' do not work as they should and prompts given need to be quite specific or need to help push the Large Language Model in the right direction in terms of what to look for or do.

A link to some of the questions used is given here:

[ChatGPT Conversation](https://chat.openai.com/share/ebb5d55e-acf1-4ee8-ae47-79fa99b04608)
